language: python
python:
  - "2.7"
  - "3.5"
cache: pip
install:
  - pip install --upgrade pip
  - pip install --upgrade wheel
  - pip install --upgrade setuptools
  - pip install --upgrade codecov pytest pytest-cov travis-sphinx
  - pip install -r requirements.txt
  - pip install .
script:
  - travis-sphinx build
  - py.test --cov DashPykpi --cov-report xml --cov-report term
after_success:
  - travis-sphinx deploy
  - codecov
